// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecommerce.Data;

namespace ecommerce.Migrations
{
    [DbContext(typeof(EcomDbContext))]
    [Migration("20180712021639_seeded")]
    partial class seeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ecommerce.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("Sku");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new { ID = 1, Description = "Make a squirrel who eats from this feeder look like it had a massive cat face", Image = "https://cdn.shopify.com/s/files/1/1365/2497/products/Cat-Head-Squirrel-Feeder_1600x.jpg?v=1520533809", Name = "Cat Head Squirrel Feeder", Price = 14.99m, Sku = "MNAG0001" },
                        new { ID = 2, Description = "A tin of mints featuring a squirrel in underpants. Keep your breathe nutty fresh.", Image = "https://cdn.shopify.com/s/files/1/1365/2497/products/Squirrel-in-Underpants-Mints_1600x.jpg?v=1520533849", Name = "Squirrel in Underpants Mints", Price = 3.99m, Sku = "MNAG0002" },
                        new { ID = 3, Description = "Ever wanted your hand to be a squirrel? Now you can with these finger puppets. Includes four paws and a squirrel head.", Image = "https://cdn.shopify.com/s/files/1/1365/2497/products/handisquirrel-Box_1600x.jpg?v=1520533725", Name = "Handisquirrel - Squirrel Finger Puppet", Price = 6.99m, Sku = "MNAG0003" },
                        new { ID = 4, Description = "Ever wanted your hand to be a squirrel? Now you can with these finger puppets. Includes four paws and a squirrel head.", Image = "https://cdn.shopify.com/s/files/1/1365/2497/products/handisquirrel-Box_1600x.jpg?v=1520533725", Name = "Handisquirrel - Squirrel Finger Puppet", Price = 6.99m, Sku = "MNAG0004" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
